# relative paths relative to where node is called (usually will be the top level of the repo)
imagedir: C:\Users\ktkm\Desktop\h\cg
# imagedir: C:\Users\ktkm\Desktop\h\3d
# imagedir: C:\Users\ktkm\Desktop\test

thumbnaildir: ./thumbnaildata
# thumbnaildir: ./thumbnaildata2

# to use, cloudkey json must be in config folder and be named "cloudkey.json"
google_cloud_config:
  enabled: true
  mainimage_bucket: ktkm-albumviewer-images

port: 80
static_serve: true
thumbnail_gen_batch: 6